keenethics/keenethics

imports/api/lib/methods.js, imports/api/lib/news.js
=> change cookies for medium

components/blog/posts.js, pages/contacts.js, pages/index.js, postsort.config.js, server.js
=> change posts sorting

pages/project-pree.js, pages/project-self-leaders.js, pages/project-the-check-network.js, pages/project-workbooking.js
Task - https://keenethics.teamwork.com/#tasks/21248048
=> Dev - Fixes

README.md, components/contacts/estimate-form.js, navigation/main.json, package-lock.json, package.json, styles/background.scss
- simplify animation
- add missed package
- change README file
- remove Career section
=> Simplify animation

posts/1545289200000-why-should-you-choose-agencies-over-freelancers-in-outsourcing.md
@epaminond Это SEO правки для этой статьи https://keenethics.teamwork.com/#tasks/21691770
=> 'Why should you choose agencies' SEO Fixes

components/blog/posts.js, package.json, pages/post.js, posts/1548831600000-creating-corporate-culture.md
@epaminond Here was corrected title of 'Creating Corporate Culture' article and I removed the 
'tinytime' package - he returned month name with misprint (Febuary).
=> Blog bugs fix

components/subscribe-for-updates/index.js, deploy, deploy-staging, server/index.js
https://trello.com/c/DgqZ4agT/17-blog-subscribe
=> Implement blog subscribe endpoint

styles/blog.scss
https://keenethics.teamwork.com/#/tasks/25882821
=> Fix btn position

.env.example, README.md, server/index.js
We would need to change env variables on staging and production (if they are quoted).
=> contact form seems to be fixed

server/index.js
=> contact form fixed

components/blocks/industries/Industries.jsx, components/blocks/tech-stack/TechStack.jsx, pages/home-page-footer.js, pages/our-services.js, styles/content.scss, styles/main-blocks/home-footer.scss, styles/pages.scss
https://trello.com/c/aHJCpUqu/1-home-scroll-down-to-learn-more-button-doesnt-do-anything
+footer links
=> Fix. Footer new design links

pages/contacts.js
[link to the issue](https://trello.com/c/Opc9hAyX/19-footer-free-estimate-button-%D0%BC%D0%B0%D1%94-%D0%B2%D0%B5%D1%81%D1%82%D0%B8-%D0%BD%D0%B0-free-estimate-form)
=> Fix button 'Free estimate'

components/categories-filter/CategoriesFilter.jsx
https://trello.com/c/MWSr75nU/4-home-page-our-projects-section-filter-wrapper-doesnt-show-all-filters-change-the-list-of-filters
=> Fix. Portflio filter show all items in a row

components/blocks/footer/footer-slider.jsx, package.json, pages/home-page-footer.js, styles/main-blocks/home-footer.scss
- Footer. Privacy Statement & Terms of Use. зменшити розмір шрифта на 2 пункти
- Footer. Latest in Blog. Latest in Blog має бути посиланням
- Footer. Latest in Blog. Дата на статтях має бути апперкейсом
- Footer. Latest in Blog Не працюють лінки на останні статті
=> Small fixes on footer

styles/main-blocks/home-footer.scss
https://trello.com/c/IJk0MhIA/44-%D1%96%D0%BD%D1%82%D0%B5%D1%80%D0%B2%D0%B0%D0%BB%D0%B8-%D0%B2-%D1%84%D1%83%D1%82%D0%B5%D1%80%D1%96
=> Footer titles margins

components/layout/main.js, components/layout/navigation/main.js, components/layout/navigation/point.js, styles/main-blocks/home-footer.scss
https://trello.com/c/1uVuIEGK/97-fix-the-burger-menu-on-mobile
=> Hamburger menu fix

components/blocks/industries/Industries.jsx, pages/services-development-and-quality-assurance.js, pages/services-education-software-development.js, pages/services-indoor-positioning-system-development.js, pages/services-non-profit-software-development.js, pages/services-ui-ux-design.js, pages/services-web-development-node.js, pages/tech-apps-phonegap.js, pages/tech-front-end-aurelia.js, pages/tech-front-end-vue.js, styles/main-blocks/lets-start.scss
- Fixed LetsStart component margin
- Removed text before LestStart component
- Fixed 2 typos:
https://trello.com/c/CUxYrwXZ/112-home-page-non-profit-service-page
https://trello.com/c/voIop7rd/262-home-page-logistics
=> LetsStart block fix and typos

components/blocks/industries/Industries.jsx
Task:
https://trello.com/c/KSj8L04N/272-home-page-industries-there-is-no-hover-for-industries-links
=> Main page. Hover for Industries. 

components/layout/footer.js, navigation/main.json
Task : https://trello.com/c/jBJ0BU0Z/90-footer-typo-on-the-about-us-page
=> Typo fixes

components/blocks/industries/Industries.jsx
Task:
https://trello.com/c/PhPtVVnc/147-home-page-real-estate-software-development
=> Real Estate link added

pages/services-education-software-development.js
Task:
https://trello.com/c/nJd8KUEQ/244-change-content-for-the-education-service-page
=> Sections order change

data/leaders.js
Task: 
https://trello.com/c/J8xyQISr/291-about-us-page-change-people-in-our-meet-our-leaders-section#comment-5fec6220619fd56c8d25cf76
=> Title for Olga Boichuk changed

components/layout/navigation/point.js
task https://trello.com/c/9OpO2Qlo/117-contact-us-please-make-the-contact-us-menu-button-clickable
=> make contact us clickable after submiting form

components/blocks/industries/Industries.jsx, components/layout/footer.js, navigation/main.json, navigation/works.json
Tasks:
https://trello.com/c/bllIV2r7/266-projects-there-are-two-real-estate-buttons-incorrect-button-work
https://trello.com/c/MWSr75nU/4-change-the-list-of-industries-home-page-footer-menu-projects
=> Projects and Portfolio changes. Industries order changes

pages/post.js, styles/blog.scss
Task:
https://trello.com/c/UlwOU88w/290-fix-the-code-snippet-functionality
@melvit 
Already merged into devops_deploy.
=> Blog articles rendering fixed

pages/referral-program.js
Task:
https://trello.com/c/TzbUqOIE/224-referral-the-mobile-keyboards-get-in-the-way-of-choosing-a-country
=> Country selector behavior fixed on mobile

components/contacts/contact-form.js, pages/contacts.js, server/autoReplyMailOptions.js
https://trello.com/c/s2XdgRjD/299-contact-us-form-change-representatives
=> Contact Us form. Change Representatives
